### ISSUE TITLE
NCBIminer reports an error

### ISSUE THREAD

**Issue by hlstrived** [greengirl/NCBIminer#3]
Hello,
I am downloading the sequence using NCBIminer_v3.01_win_64 and the configuration file I am using is as follows:
# GenBank defined feature types
feature type:
misc_feature
rRNA

feature name:# Gene or loci names and its alias. One gene is supported
ITS 2
ITS 1
5.8S
internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2

#One or more DNA sequences of the interested gene or loci in fasta format, which will be used in the 
#BLAST to search for references sequences for the target group. Use complete sequence if possible.
initial query:
>U63164.1 Pseudopanax anomalus 18S ribosomal RNA gene, partial sequence, internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2, complete sequence, and 28S ribosomal RNA, partial sequence
GAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCACAGCAGAACGA
CCCGCGAACACGTTACAACACCGGGTGAGGGACGAAGGGTGMGCAAGTTCCCCAAGTCGCGAACCCATGGTCGGGGATCGCCCTCGGGTGGTCCTCGTCCGAACAACGACCCCCCGGCGCGGAATGCGCCAAGGAAATCAAACTGAACTGCACGTGTCCCCCCCGTTTGCGGGCGGCGGAGGCGTCTTTCTAAAACACAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGA
ATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCATTAGGCCGAGGGCACGTCTGCCT
GGGCGTCACGCATCGCGTNNCCCCCAACCCCTCACTCCCTCATGGGAGTCGGGGCGGAGGGGCGGATAATGGCCTCCCGTGTCTCACCGCGCGGTTGGCCCAAATGCGAGTCCTTGGCGACGGACGTCACGACAAGTGGTGGTTGTAAAAAGCCCTATTCTCCTGTCGTGCGGTGACCCGTCTCCAATAAAAGCTCTCGTGACCCTGTTD
CGCCGTCCTCGACGTGMGCTCCGACCGCGACCCCAGGTCAGGCGGGACTACCCGCTGAGTTTAAGCATAT
CAATAAGCGGAGGA

# Define your taxon list. The part before "\" was used to serach target query seqences 
# in BLAST which were used to blast the part after "\" (target groups).
taxon list:
Raukaua\Raukaua anomalus

When I run NCBIminer on windows 10. The error I get is as follows:
Error in data.txt (line 1)
Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blast_new.m (line 31)
Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blastref.m (line 23)
Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer\NCBIminer.m (line 54)
Job finish but there is an error, please check the log fiel: Raukaua1_log.txt

I tried to modify the configuration file to cds and gene, but this problem still occurs. Could you help me solve it? 

Thank you so much

Best regards,

Ling

**Comment by greengirl** [comment]
Dear Ling
NCBIminer has been updated to PyNCBIminer. Now it is almost ready. You can accsess it through https://github.com/Xiaoting-Xu/PyNCBIminer. We would like to have your feedbacks to improve the software.

Best wishes

Xiaoting

从 Windows 版邮件发送

发件人: hlstrived
发送时间: 2024年2月28日 14:34
收件人: greengirl/NCBIminer
抄送: Subscribed
主题: [greengirl/NCBIminer] NCBIminer reports an error (Issue #3)

Hello,
I am downloading the sequence using NCBIminer_v3.01_win_64 and the configuration file I am using is as follows:
GenBank defined feature types
feature type:
misc_feature
rRNA
feature name:# Gene or loci names and its alias. One gene is supported
ITS 2
ITS 1
5.8S
internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2
#One or more DNA sequences of the interested gene or loci in fasta format, which will be used in the
#BLAST to search for references sequences for the target group. Use complete sequence if possible.
initial query:
U63164.1 Pseudopanax anomalus 18S ribosomal RNA gene, partial sequence, internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2, complete sequence, and 28S ribosomal RNA, partial sequence
GAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCACAGCAGAACGA
CCCGCGAACACGTTACAACACCGGGTGAGGGACGAAGGGTGMGCAAGTTCCCCAAGTCGCGAACCCATGGTCGGGGATCGCCCTCGGGTGGTCCTCGTCCGAACAACGACCCCCCGGCGCGGAATGCGCCAAGGAAATCAAACTGAACTGCACGTGTCCCCCCCGTTTGCGGGCGGCGGAGGCGTCTTTCTAAAACACAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGA
ATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCATTAGGCCGAGGGCACGTCTGCCT
GGGCGTCACGCATCGCGTNNCCCCCAACCCCTCACTCCCTCATGGGAGTCGGGGCGGAGGGGCGGATAATGGCCTCCCGTGTCTCACCGCGCGGTTGGCCCAAATGCGAGTCCTTGGCGACGGACGTCACGACAAGTGGTGGTTGTAAAAAGCCCTATTCTCCTGTCGTGCGGTGACCCGTCTCCAATAAAAGCTCTCGTGACCCTGTTD
CGCCGTCCTCGACGTGMGCTCCGACCGCGACCCCAGGTCAGGCGGGACTACCCGCTGAGTTTAAGCATAT
CAATAAGCGGAGGA
Define your taxon list. The part before "" was used to serach target query seqences
in BLAST which were used to blast the part after "" (target groups).
taxon list:
Raukaua\Raukaua anomalus
When I run NCBIminer on windows 10. The error I get is as follows:
Error in data.txt (line 1)
Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blast_new.m (line 31)
Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blastref.m (line 23)
Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer\NCBIminer.m (line 54)
Job finish but there is an error, please check the log fiel: Raukaua1_log.txt
I tried to modify the configuration file to cds and gene, but this problem still occurs. Could you help me solve it?
Thank you so much
Best regards,
Ling

**Comment by hlstrived** [comment]
> Dear Ling NCBIminer has been updated to PyNCBIminer. Now it is almost ready. You can accsess it through https://github.com/Xiaoting-Xu/PyNCBIminer. We would like to have your feedbacks to improve the software. Best wishes Xiaoting 从 Windows 版邮件发送 发件人: hlstrived 发送时间: 2024年2月28日 14:34 收件人: greengirl/NCBIminer 抄送: Subscribed 主题: [greengirl/NCBIminer] NCBIminer reports an error (Issue #3) Hello, I am downloading the sequence using NCBIminer_v3.01_win_64 and the configuration file I am using is as follows: GenBank defined feature types feature type: misc_feature rRNA feature name:# Gene or loci names and its alias. One gene is supported ITS 2 ITS 1 5.8S internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2 #One or more DNA sequences of the interested gene or loci in fasta format, which will be used in the #BLAST to search for references sequences for the target group. Use complete sequence if possible. initial query: U63164.1 Pseudopanax anomalus 18S ribosomal RNA gene, partial sequence, internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2, complete sequence, and 28S ribosomal RNA, partial sequence GAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCACAGCAGAACGA CCCGCGAACACGTTACAACACCGGGTGAGGGACGAAGGGTGMGCAAGTTCCCCAAGTCGCGAACCCATGGTCGGGGATCGCCCTCGGGTGGTCCTCGTCCGAACAACGACCCCCCGGCGCGGAATGCGCCAAGGAAATCAAACTGAACTGCACGTGTCCCCCCCGTTTGCGGGCGGCGGAGGCGTCTTTCTAAAACACAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGA ATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCATTAGGCCGAGGGCACGTCTGCCT GGGCGTCACGCATCGCGTNNCCCCCAACCCCTCACTCCCTCATGGGAGTCGGGGCGGAGGGGCGGATAATGGCCTCCCGTGTCTCACCGCGCGGTTGGCCCAAATGCGAGTCCTTGGCGACGGACGTCACGACAAGTGGTGGTTGTAAAAAGCCCTATTCTCCTGTCGTGCGGTGACCCGTCTCCAATAAAAGCTCTCGTGACCCTGTTD CGCCGTCCTCGACGTGMGCTCCGACCGCGACCCCAGGTCAGGCGGGACTACCCGCTGAGTTTAAGCATAT CAATAAGCGGAGGA Define your taxon list. The part before "" was used to serach target query seqences in BLAST which were used to blast the part after "" (target groups). taxon list: Raukaua\Raukaua anomalus When I run NCBIminer on windows 10. The error I get is as follows: Error in data.txt (line 1) Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blast_new.m (line 31) Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blastref.m (line 23) Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer\NCBIminer.m (line 54) Job finish but there is an error, please check the log fiel: Raukaua1_log.txt I tried to modify the configuration file to cds and gene, but this problem still occurs. Could you help me solve it? Thank you so much Best regards, Ling — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Dear Xiaoting:
Thank you very much for your prompt response. I truly appreciate your suggestion to download and try PyNCBIminer. Following your advice, I will give it another attempt. 

Best regards,
Ling

**Comment by hlstrived** [comment]
> Dear Ling NCBIminer has been updated to PyNCBIminer. Now it is almost ready. You can accsess it through https://github.com/Xiaoting-Xu/PyNCBIminer. We would like to have your feedbacks to improve the software. Best wishes Xiaoting 从 Windows 版邮件发送 发件人: hlstrived 发送时间: 2024年2月28日 14:34 收件人: greengirl/NCBIminer 抄送: Subscribed 主题: [greengirl/NCBIminer] NCBIminer reports an error (Issue #3) Hello, I am downloading the sequence using NCBIminer_v3.01_win_64 and the configuration file I am using is as follows: GenBank defined feature types feature type: misc_feature rRNA feature name:# Gene or loci names and its alias. One gene is supported ITS 2 ITS 1 5.8S internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2 #One or more DNA sequences of the interested gene or loci in fasta format, which will be used in the #BLAST to search for references sequences for the target group. Use complete sequence if possible. initial query: U63164.1 Pseudopanax anomalus 18S ribosomal RNA gene, partial sequence, internal transcribed spacer 1, 5.8S ribosomal RNA gene, and internal transcribed spacer 2, complete sequence, and 28S ribosomal RNA, partial sequence GAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTGTCGAAACCTGCACAGCAGAACGA CCCGCGAACACGTTACAACACCGGGTGAGGGACGAAGGGTGMGCAAGTTCCCCAAGTCGCGAACCCATGGTCGGGGATCGCCCTCGGGTGGTCCTCGTCCGAACAACGACCCCCCGGCGCGGAATGCGCCAAGGAAATCAAACTGAACTGCACGTGTCCCCCCCGTTTGCGGGCGGCGGAGGCGTCTTTCTAAAACACAAACGACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGAATTGCAGA ATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCATTAGGCCGAGGGCACGTCTGCCT GGGCGTCACGCATCGCGTNNCCCCCAACCCCTCACTCCCTCATGGGAGTCGGGGCGGAGGGGCGGATAATGGCCTCCCGTGTCTCACCGCGCGGTTGGCCCAAATGCGAGTCCTTGGCGACGGACGTCACGACAAGTGGTGGTTGTAAAAAGCCCTATTCTCCTGTCGTGCGGTGACCCGTCTCCAATAAAAGCTCTCGTGACCCTGTTD CGCCGTCCTCGACGTGMGCTCCGACCGCGACCCCAGGTCAGGCGGGACTACCCGCTGAGTTTAAGCATAT CAATAAGCGGAGGA Define your taxon list. The part before "" was used to serach target query seqences in BLAST which were used to blast the part after "" (target groups). taxon list: Raukaua\Raukaua anomalus When I run NCBIminer on windows 10. The error I get is as follows: Error in data.txt (line 1) Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blast_new.m (line 31) Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer_3.01\blastref.m (line 23) Error in C:\Users\UNIS\AppData\Local\Temp\UNIS\mcrCache8.4\NCBImi0\NCBIminer\NCBIminer.m (line 54) Job finish but there is an error, please check the log fiel: Raukaua1_log.txt I tried to modify the configuration file to cds and gene, but this problem still occurs. Could you help me solve it? Thank you so much Best regards, Ling — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
